version: "3.7"

services:
  zomboi:
    build: .
    volumes:
      - /path/to/maps:/root/steam/steamapps/common/ProjectZomboid/media/maps
      - /path/to/logs:/root/Zomboid/Logs
    environment:
      DISCORD_TOKEN: "my_bot_token"
      CHANNEL: "channel_name_or_id"
      RCON_PASSWORD: "my_rcon_password"
    restart: unless-stopped
